services:
  hub:
    build:
      context: .
      args:
        - NB_USER
        - USER_DIR
        - SPYGLASS_BASE_DIR
        - PAPER_ID
        - MYSQL_USER
        - MYSQL_HOST
        - MYSQL_ROOT_PASSWORD
        - CONTAINER_PAPER_DIR
        - SPYGLASS_PAPER_DIR
      dockerfile: Dockerfile
    container_name: hub
    env_file: .env
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:${CONTAINER_NOTEBOOK_DIR}
      - ./config/.datajoint_config.json:${CONTAINER_DJ_CONFIG}
      - conda:/opt/conda
    depends_on:
      - db

  db:
    image: datajoint/mysql:8.0
    container_name: db
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/entrypoint_db.sh:/entrypoint_db.sh
      - ./export_files:/docker-entrypoint-initdb.d
    restart:
      on-failure
    entrypoint: ["/bin/bash", "/entrypoint_db.sh"]

networks:
  spyglass_network:
    name: spyglass_net
volumes: # Docker managed mappings.
  conda: # Saves time declaring env
  db_data: # Allows persistent db data
