services:
  hub:
    build:
      context: .
      args:
        - PAPER_ID
      dockerfile: Docker_hub.Dockerfile
    container_name: hub
    env_file: .env
    ports:
      - "8888:8888"
    volumes:
      - conda:/opt/conda
      - notebooks:/home/joyvan/notebooks
    depends_on:
      - db

  db:
    build:
      context: .
      args:
        - MYSQL_USER
        - MYSQL_HOST
        - MYSQL_ROOT_PASSWORD
        - MYSQL_ROOT_HOST
      dockerfile: Docker_db.Dockerfile
    container_name: db
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - db_data:/var/lib/mysql
      - ./grant_root_permissions.sql:/docker-entrypoint-initdb.d/grant_root_permissions.sql
    restart:
      on-failure

networks:
  spyglass_network:
    name: spyglass_net

volumes: # Docker managed mappings.
  conda: # Saves time declaring env
  notebooks: # Saves user notebook edits
  db_data: # Allows persistent db data

