services:
  hub:
    build:
      context: .
      args:
        - PAPER_ID
        - MYSQL_USER
        - MYSQL_HOST
        - MYSQL_PASSWORD
        - CONTAINER_PAPER_DIR
        - SPYGLASS_PAPER_DIR
      dockerfile: Dockerfile
    container_name: hub
    ports:
      - "8888:8888"
    # entrypoint: ["/entrypoint.sh"]
    env_file: .env
    volumes:
      - ./notebooks:${CONTAINER_NOTEBOOK_DIR}
      - ./config/.datajoint_config.json:${CONTAINER_DJ_CONFIG}
      # - ./config/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
      # - ./config/jupyter_jupyterlab_server_config.py:/etc/jupyter/jupyter_jupyterlab_server_config.py
      # - ./config/entrypoint.sh:/entrypoint.sh
      # - ./config/entrypoint.py:/entrypoint.py
      - ./export_files/:/export_files/
    # entrypoint: ["start-singleuser.py"]
    depends_on:
      - db

  db:
    image: datajoint/mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/entrypoint_db.sh:/entrypoint_db.sh
      - ./export_files:/docker-entrypoint-initdb.d
    env_file: .env
    restart:
      on-failure
    # entrypoint: ["/bin/bash", "/entrypoint_db.sh"]

networks:
  spyglass_network:
    name: spyglass_net
volumes:
  db_data:
