services:
  hub:
    build:
      context: .
      args:
        - PAPER_ID
      dockerfile: Docker_hub.Dockerfile
    container_name: ${PAPER_ID}_hub
    env_file: .env
    ports:
      - "${HUB_PORT}:8888"
    volumes:
      - ${PAPER_ID}_conda:/opt/conda
      - ${PAPER_ID}_notebooks:/home/jovyan/notebooks
    depends_on:
      - db

  db:
    build:
      context: .
      args:
        - MYSQL_USER
        - MYSQL_HOST
        - MYSQL_ROOT_PASSWORD
        - MYSQL_ROOT_HOST
      dockerfile: Docker_db.Dockerfile
    container_name: ${PAPER_ID}_db
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ${PAPER_ID}_db_data:/var/lib/mysql
      - ./config/grant_root_permissions.sql:/docker-entrypoint-initdb.d/grant_root_permissions.sql
    restart:
      on-failure

networks:
  spyglass_network:
    name: spyglass_net

volumes: # Docker managed mappings.
  ${PAPER_ID}_conda: # Saves time declaring env
  ${PAPER_ID}_notebooks: # Saves user notebook edits
  ${PAPER_ID}_db_data: # Allows persistent db data
