services:
  hub:
    container_name: ${PAPER_ID}_hub
    env_file: .env
    image: "${HUB_IMAGE_NAME}"
    ports:
      - "${SPYGLASS_HUB_PORT}:8888"
    volumes:
      - conda:/opt/conda
      - notebooks:/home/jovyan/notebooks
    depends_on:
      - db
    networks:
      - spyglass_network

  db:
    container_name: ${PAPER_ID}_db
    image: "${DB_IMAGE_NAME}"
    env_file: .env
    ports:
      - "${SPYGLASS_DB_PORT}:3306"
    volumes:
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - db_data:/var/lib/mysql
    networks:
      - spyglass_network
    restart:
      on-failure

networks:
  spyglass_network:
    name: spyglass_net

volumes: # Docker managed mappings.
  conda: # Saves time declaring env
    name: "${PAPER_ID}_conda"
  notebooks: # Saves user notebook edits
    name: "${PAPER_ID}_notebooks"
  db_data: # Allows persistent db data
    name: "${PAPER_ID}_db_data"
