name: paper2
channels:
  - conda-forge
  - defaults
  - franklab
  - edeno
  # - pytorch # dlc-only
  # - anaconda  # dlc-only, for cudatoolkit
dependencies:
  - bottleneck
  # - cudatoolkit=11.3 # dlc-only
  # - ffmpeg # dlc-only
  - ipympl
  - jupyterlab>=3.*
  # - libgcc # dlc-only
  - matplotlib
  - non_local_detector
  - numpy<1.24
  - pip
  - position_tools
  - pybind11  # req by mountainsort4 -> isosplit5
  - pydotplus
  - pyfftw<=0.12.0  # ghostipy req. install from conda-forge for Mac ARM
  - python>=3.9,<3.10
  - pytorch<1.12.0
  - ripple_detection
  - seaborn
  # - torchaudio # dlc-only
  # - torchvision # dlc-only
  - track_linearization>=2.3
  - pip:
      # - ghostipy # for common_filter
      # - mountainsort4
      - git+https://github.com/LorenFrankLab/spyglass.git
      - spyglass-neuro
